"""add servicio and duracion_minutos to citas

Revision ID: db1d9a5bdb31
Revises: 52925e92195c
Create Date: 2025-12-09 14:44:10.455881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1d9a5bdb31'
down_revision: Union[str, Sequence[str], None] = '52925e92195c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citas', sa.Column('servicio', sa.String(length=100), nullable=True))
    op.add_column('citas', sa.Column('duracion_minutos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citas', 'duracion_minutos')
    op.drop_column('citas', 'servicio')
    # ### end Alembic commands ###
